#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Make sure all the test scripts are executable
chmod +x scripts/*.sh
# Clear the tmp directory
rm -f tmp/*

# This flag will be tripped if any tests fail
all_tests_passed=true

for test_script in scripts/*.sh; do
	test_name=${test_script//.sh/}
	test_name=${test_name//scripts\//}

	echo -n "Running \"$test_name\"... "
	
	PATH="$(realpath "$(pwd)/../"):$PATH"
	export PATH

	if [[ "$("$test_script")" == "0" ]]; then
		echo "pass" > "results/$test_name"
		echo -e "${GREEN}PASSED.${NC}"
	else
		echo "fail" > "results/$test_name"
		echo -e "${RED}FAILED.${NC}"
		all_tests_passed=false
	fi
done

if [[ "$all_tests_passed" == "true" ]]; then
	echo -e "${GREEN}All tests OK.${NC}"
else
	echo -e "${RED}There were failed tests.${NC}"
	echo "Debug info is available in debug/"
fi