#!/usr/bin/env bash

if [[ "$(basename "$(pwd)")" != "tests" ]] || [[ ! -f "$(pwd)/run-tests" ]]; then
	echo "This script must be run from the 'tests' subdirectory"
	exit
fi

if [ -t 1 ]; then
	# Colorized output only if we're outputting to a tty
	RED='\033[0;31m'
	GREEN='\033[0;32m'
	NC='\033[0m' # No Color
fi

# Make sure all the test scripts are executable
chmod +x scripts/*.sh
# Clear the tmp directory
rm -f tmp/*
# Clear debug output from previous tests
rm -f debug/*

# This flag will be tripped if any tests fail
all_tests_passed=true

for test_script in scripts/*.sh; do
	test_name=${test_script//.sh/}
	test_name=${test_name//scripts\//}

	echo -n "Running \"$test_name\"... "
	
	PATH="$(realpath "$(pwd)/../bin/"):$PATH"
	export PATH

	if [[ "$("$test_script")" == "0" ]]; then
		echo "pass" > "results/$test_name"
		echo -e "${GREEN}PASSED.${NC}"
	else
		echo "fail" > "results/$test_name"
		echo -e "${RED}FAILED.${NC}"
		all_tests_passed=false
	fi
done

if [[ "$all_tests_passed" == "true" ]]; then
	echo -e "${GREEN}All tests OK.${NC}"
else
	echo -e "${RED}There were failed tests.${NC}"
	echo "Debug info is available in debug/"
fi
