#!/usr/bin/env bash

function run_polonius_reader_or_editor() {
	local reader="$1" file_name="$2"
	local -n raw_parameters_array="$3"
	local get_output="$4" return_code="" output="" result=""
	if [[ $reader -eq 1 ]]; then
		# Running polonius-reader
		if [[ $get_output -eq 1 ]]; then
			# Getting output, not return code
			result="$(polonius-reader "tmp/$file_name" "${raw_parameters_array[@]}" 2>/dev/null)"
		else
			# Getting return code
			polonius-reader "tmp/$file_name" "${raw_parameters_array[@]}" >/dev/null 2>&1
			result=$?
		fi
	else
		# Running polonius-editor
		polonius-editor "tmp/$file_name" "${raw_parameters_array[@]}" >/dev/null 2>&1
		return_code=$?
		output="$(cat "tmp/$file_name" 2>/dev/null)"

		if [[ $get_output -eq 1 ]]; then
			result="$output"
		else
			result="$return_code"
		fi
	fi
	echo "$result"
}

function execute_instruction() {
	# Returns the return code or resulting file contents from polonius-editor
	local instruction="$1" file_name="$2" get_output="$3" return_code="" output="" passed_args=()

	passed_args+=("-a")
	passed_args+=("$instruction")

	result="$(run_polonius_reader_or_editor 0 "$file_name" "passed_args" "$get_output")"
	echo "$result"
}

function prepare_a_file_for_instruction() {
	local new_file="$1" file_name="$2"

	if [[ "$file_name" == "" ]]; then
		file_name="$(basename "$(mktemp -u)")"
	fi

	if [[ "$new_file" == "1" ]]; then
		rm -f "tmp/${file_name:?}"
	fi
	
	echo "$file_name"
}

function get_output_of_instruction() {
	local instruction="$1" test_name="$2" new_file="$3" file_name="$4"

	file_name=$(prepare_a_file_for_instruction "$new_file" "$file_name")
	output=$(execute_instruction "$instruction" "$file_name" 1)

	rm -f "tmp/${file_name:?}"

	echo "$output"
}

function check_output_of_instruction_is_correct() {
	local expected_output="$1" instruction="$2" test_name="$3" new_file="$4" file_name="$5" actual_output=""

	actual_output="$(get_output_of_instruction "$instruction" "$test_name" "$new_file" "$file_name")"

	if [[ "$expected_output" == "$actual_output" ]]; then
		# Everything OK
		true
	else
		export all_ok=1 # Everything not OK
		{
			echo "--"
			echo "INSTRUCTION: $instruction"
			echo "Expected result: $expected_output"
			echo "Actual result: $actual_output"
			echo "File name: tmp/$file_name"
		}  >> "debug/${test_name:?}"
	fi
}

function check_instruction() {
	local instruction="$1" test_name="$2" should_return_zero="$3" file_should_exist="$4" new_file="$5" file_name="$6" return_code="" file_exists="" returned_correctly=0

	file_name=$(prepare_a_file_for_instruction "$new_file" "$file_name")
	return_code=$(execute_instruction "$instruction" "$file_name")

	file_exists=$([[ -f "tmp/$file_name" ]] && echo 1 || echo 0)

	rm -f "tmp/${file_name:?}"

	if [[ $should_return_zero -eq 0 ]] && [[ $return_code -ne 0 ]]; then
		returned_correctly=1
	elif [[ $should_return_zero -eq 1 ]] && [[ $return_code -eq 0 ]]; then
		returned_correctly=1
	else
		returned_correctly=0
	fi

	if [[ $returned_correctly -eq 1 ]] && [[ $file_exists -eq $file_should_exist ]]; then
		# Everything OK
		true
	else
		export all_ok=1 # Everything not OK
		{
			echo "--"
			echo "INSTRUCTION: $instruction"
			echo "Return code: $return_code"
			echo "Should return 0?: $should_return_zero"
			echo "File exists?: $file_exists"
			echo "File should exist?: $file_should_exist"
			echo "File name: tmp/$file_name"
		}  >> "debug/${test_name:?}"
	fi
}

function create_test_file() {
	# Returns the new test file name
	local contents="$1" name="$2"
	
	if [[ "$name" == "" ]]; then
		name="$(basename "$(mktemp -u)")"
	fi

	echo "$contents" > "tmp/${name:?}"
	echo "$name"
}
